name: build
on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: setup-graalvm-ce
        uses: rinx/setup-graalvm-ce@v0.0.5
        with:
          graalvm-version: "20.2.0"
          java-version: "java11"
          native-image: "true"
      - name: Build & Unit tests
        run: mvn --batch-mode clean package
      - name: Native build
        run: mvn --batch-mode package -DskipTests -Dnative
      - name: Integration tests
        run: mvn --batch-mode package -Dskip.surefire.tests=true failsafe:integration-test failsafe:verify